In [2]:
!pip install textblob

Collecting textblob
  Downloading textblob-0.20.1-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\datamites\anaconda3\lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in c:\users\datamites\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in c:\users\datamites\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\datamites\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\datamites\anaconda3\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\datamites\anaconda3\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.20.1-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   --------------------------------- ------ 524.3/625.0 kB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 625.0/625.0 kB 2.1 MB/s  0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.20.1

In [3]:
import pandas as pd
from textblob import TextBlob

In [4]:
df = pd.read_excel('sentiment_dataset_1000.xlsx')

In [5]:
df

       id                              text actual_label
0       1          The room has two windows      Neutral
1       2                 Worth every penny     Positive
2       3         The package arrived today      Neutral
3       4            Delivery was very late     Negative
4       5                 I bought a laptop      Neutral
..    ...                               ...          ...
995   996                  This made my day     Positive
996   997               Not worth the money     Negative
997   998       Very happy with the service     Positive
998   999         The package arrived today      Neutral
999  1000  This product is available online      Neutral

[1000 rows x 3 columns]

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1000 non-null   int64
 1   text          1000 non-null   object
 2   actual_label  1000 non-null   object
dtypes: int64(1), object(2)
memory usage: 23.6+ KB
None

In [7]:
df['actual_label'].value_counts()

actual_label
Positive    334
Neutral     333
Negative    333
Name: count, dtype: int64

In [8]:
def pred(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return 'Positive'
    elif polarity < 0:
        return 'Negative'
    else:
        return 'Neutral'

df['predicted_label'] = df['text'].apply(pred)

In [9]:
df['predicted_label']

0       Neutral
1      Positive
2       Neutral
3      Negative
4       Neutral
         ...
995     Neutral
996    Negative
997    Positive
998     Neutral
999    Positive
Name: predicted_label, Length: 1000, dtype: object

In [10]:
df['polarity'] = df['text'].apply(lambda x: TextBlob(x).sentiment.polarity)
df['subjectivity'] = df['text'].apply(lambda x: TextBlob(x).sentiment.subjectivity)
df.head()

,id,text,actual_label,predicted_label,polarity,subjectivity
0,1,The room has two windows,Neutral,Neutral,0.00,0.00
1,2,Worth every penny,Positive,Positive,0.30,0.10
2,3,The package arrived today,Neutral,Neutral,0.00,0.00
3,4,Delivery was very late,Negative,Negative,-0.39,0.78
4,5,I bought a laptop,Neutral,Neutral,0.00,0.00

In [11]:
df

,id,text,actual_label,predicted_label,polarity,subjectivity
0,1,The room has two windows,Neutral,Neutral,0.00,0.00
1,2,Worth every penny,Positive,Positive,0.30,0.10
2,3,The package arrived today,Neutral,Neutral,0.00,0.00
3,4,Delivery was very late,Negative,Negative,-0.39,0.78
4,5,I bought a laptop,Neutral,Neutral,0.00,0.00
...,...,...,...,...,...,...
995,996,This made my day,Positive,Neutral,0.00,0.00
996,997,Not worth the money,Negative,Negative,-0.15,0.10
997,998,Very happy with the service,Positive,Positive,1.00,1.00
998,999,The package arrived today,Neutral,Neutral,0.00,0.00
999,1000,This product is available online,Neutral,Positive,0.40,0.40

In [12]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(df['actual_label'], df['predicted_label'])
print('Accuracy:', accuracy)

Accuracy: 0.909

In [13]:
df.to_excel('sentiment_analysis_results.xlsx', index=False)

In [14]:
text = "I like my new laptop"
b = TextBlob(text)

In [15]:
b.sentiment.polarity

0.13636363636363635

In [16]:
b.sentiment.subjectivity

0.45454545454545453